### ISSUE TITLE
Research possible resources for additional course metadata

### ISSUE THREAD

**Issue by au5ton** [cougargrades/publicdata#3]
- Possibly scraping http://www.uh.edu/catalog-undergraduate

**Comment by au5ton** [comment]
An existing known solution would be using CollegeScheduler as seen in the link below. A limitation of this is only having access to the course information currently available at runtime (past terms are unavailable).


https://github.com/au5ton/docs/wiki/CollegeScheduler-(*.collegescheduler.com)#get-apitermstermsubjectssubjectcoursescourse

**Comment by au5ton** [comment]
UH Publications scraping has been implemented here: https://github.com/cougargrades/publicdata/tree/6e5672d5a07fa7102add75870f1cefed9d89a1b0/documents/edu.uh.publications.courses

More work yet to be done.

**Comment by au5ton** [comment]
```
[1 / 2] Scraping http://publications.uh.edu for all possible coid values:
        => ../34/index.csv
|████████████████████████████████████████| 416/416 [100%] in 1:14:06 (0.09/s)
Traceback (most recent call last):
  File "./main.py", line 36, in <module>
    for page in iterator:
  File "/home/pi/sandbox/publicdata/documents/edu.uh.publications.courses/src/scraper.py", line 61, in __next__                                                                                                   
    return self.next()
  File "/home/pi/sandbox/publicdata/documents/edu.uh.publications.courses/src/scraper.py", line 71, in next                                                                                                       
    results = [(self.extractCoid(x['href']), x.string) for x in data]
  File "/home/pi/sandbox/publicdata/documents/edu.uh.publications.courses/src/scraper.py", line 71, in <listcomp>                                                                                                 
    results = [(self.extractCoid(x['href']), x.string) for x in data]
  File "/home/pi/sandbox/publicdata/documents/edu.uh.publications.courses/src/scraper.py", line 57, in extractCoid                                                                                                
    return parse_qs(urlparse(link).query)['coid'][0]
KeyError: 'coid'
```

**Comment by au5ton** [comment]
```
Traceback (most recent call last):
  File "./main.py", line 60, in <module>
    outfile.write(scrapeCourse(line["catoid"], line["coid"], line["catalog_title"]))
  File "/home/pi/sandbox/publicdata/documents/edu.uh.publications.courses/src/scraper.py", line 78, in scrapeCourse
    res = httpx.get(f'http://publications.uh.edu/ajax/preview_course.php?catoid={catoid}&coid={coid}&show')
  File "/usr/local/lib/python3.7/dist-packages/httpx/_api.py", line 170, in get
    trust_env=trust_env,
  File "/usr/local/lib/python3.7/dist-packages/httpx/_api.py", line 96, in request
    allow_redirects=allow_redirects,
  File "/usr/local/lib/python3.7/dist-packages/httpx/_client.py", line 601, in request
    request, auth=auth, allow_redirects=allow_redirects, timeout=timeout,
  File "/usr/local/lib/python3.7/dist-packages/httpx/_client.py", line 621, in send
    request, auth=auth, timeout=timeout, allow_redirects=allow_redirects,
  File "/usr/local/lib/python3.7/dist-packages/httpx/_client.py", line 648, in send_handling_redirects
    request, auth=auth, timeout=timeout, history=history
  File "/usr/local/lib/python3.7/dist-packages/httpx/_client.py", line 684, in send_handling_auth
    response = self.send_single_request(request, timeout)
  File "/usr/local/lib/python3.7/dist-packages/httpx/_client.py", line 719, in send_single_request
    timeout=timeout.as_dict(),
  File "/usr/local/lib/python3.7/dist-packages/httpcore/_sync/connection_pool.py", line 153, in request
    method, url, headers=headers, stream=stream, timeout=timeout
  File "/usr/local/lib/python3.7/dist-packages/httpcore/_sync/connection.py", line 78, in request
    return self.connection.request(method, url, headers, stream, timeout)
  File "/usr/local/lib/python3.7/dist-packages/httpcore/_sync/http11.py", line 62, in request
    ) = self._receive_response(timeout)
  File "/usr/local/lib/python3.7/dist-packages/httpcore/_sync/http11.py", line 115, in _receive_response
    event = self._receive_event(timeout)
  File "/usr/local/lib/python3.7/dist-packages/httpcore/_sync/http11.py", line 145, in _receive_event
    data = self.socket.read(self.READ_NUM_BYTES, timeout)
  File "/usr/local/lib/python3.7/dist-packages/httpcore/_backends/sync.py", line 62, in read
    return self.sock.recv(n)
  File "/usr/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.7/dist-packages/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc) from None
httpcore._exceptions.ReadTimeout: timed out
```

**Comment by au5ton** [comment]
Resolved: https://github.com/cougargrades/publicdata/issues/3#issuecomment-650673082

**Comment by au5ton** [comment]
Resolved https://github.com/cougargrades/publicdata/issues/3#issuecomment-650715500 in 8a7271f8606915d71af37b3bdec4dd54c758e33c

**Comment by au5ton** [comment]
Todo: Processing downloaded HTML files

**Comment by au5ton** [comment]
Implemented solution that matches `catoid` and `coid` values (from http://publications.uh.edu/) with a corresponding `department` and `catalogNumber`. See: `edu.uh.publications.courses`
